# -*- coding: utf-8 -*-
"""finalmodel (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7tteRxvURzn4xAtg5PQZ2u04fq5wWHo
"""

import torch
import torchvision.models as models
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import numpy as np
import random
from sklearn.metrics import accuracy_score, precision_score, recall_score

USE_CUDA = torch.cuda.is_available()
device = torch.device("cuda" if USE_CUDA else "cpu")

random.seed(1)
torch.manual_seed(1)
if device == 'cuda':
    torch.cuda.manual_seed_all(1)

from google.colab import drive
drive.mount('/content/drive')

!cp /content/drive/MyDrive/archive.zip ./

from google.colab import drive
drive.mount('/content/drive')

!unzip archive.zip

data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

dataset_path = "fire_dataset"
full_dataset = dsets.ImageFolder(root=dataset_path, transform=data_transforms)

train_size = int(0.6 * len(full_dataset))
val_size = int(0.2 * len(full_dataset))
test_size = len(full_dataset) - train_size - val_size

train_dataset, val_dataset, test_dataset = torch.utils.data.random_split(
    full_dataset,
    [train_size, val_size, test_size],
    generator=torch.Generator().manual_seed(1)
)

train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(dataset=val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False)

def CNN():
    model = models.efficientnet_v2_s(pretrained=True)

    for param in model.parameters():
        param.requires_grad = False

    num_ftrs = model.classifier[1].in_features
    model.classifier = nn.Linear(num_ftrs, 2)

    return model.to(device)

"""학습률 튜닝"""

lr_candidates = [0.001, 0.01, 0.1]
best_lr = None
best_val_recall = 0.0

for lr in lr_candidates:
    tuning_model = CNN()
    criterion = nn.CrossEntropyLoss().to(device)
    optimizer = torch.optim.Adam(tuning_model.classifier.parameters(), lr=lr)

    for epoch in range(3):
        tuning_model.train()
        for x_train, y_train in train_loader:
            x_train, y_train = x_train.to(device), y_train.to(device)
            outputs = tuning_model(x_train)
            cost = criterion(outputs, y_train)

            optimizer.zero_grad()
            cost.backward()
            optimizer.step()

    tuning_model.eval()
    val_preds = []
    val_targets = []

    with torch.no_grad():
        for x_val, y_val in val_loader:
            x_val, y_val = x_val.to(device), y_val.to(device)
            outputs = tuning_model(x_val)
            preds = torch.argmax(outputs, 1)
            val_preds.extend(preds.cpu().numpy())
            val_targets.extend(y_val.cpu().numpy())

    acc = accuracy_score(val_targets, val_preds)
    prec = precision_score(val_targets, val_preds, zero_division=0)
    rec = recall_score(val_targets, val_preds, zero_division=0)

    print("Learning rate: {}, Accuracy: {:.4f}, Precision: {:.4f}, Recall: {:.4f}".format(lr, acc, prec, rec))

    if rec > best_val_recall:
        best_val_recall = rec
        best_lr = lr

    print("Best Learning rate: {}".format(best_lr))

"""에포크 튜닝"""

final_model = CNN()
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(final_model.classifier.parameters(), lr=best_lr)

max_epochs = 20
patience = 3
patience_counter = 0
best_val_loss = float('inf')

for epoch in range(max_epochs):
    final_model.train()
    train_loss = 0.0
    for x_train, y_train in train_loader:
        x_train, y_train = x_train.to(device), y_train.to(device)
        outputs = final_model(x_train)
        cost = criterion(outputs, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        train_loss += cost.item() * x_train.size(0)

    train_loss /= len(train_loader.dataset)

    final_model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for x_val, y_val in val_loader:
            x_val, y_val = x_val.to(device), y_val.to(device)
            outputs = final_model(x_val)
            cost = criterion(outputs, y_val)
            val_loss += cost.item() * x_val.size(0)

    val_loss /= len(val_loader.dataset)

    print("Epoch: {}, Train Loss: {:.4f}, Val Loss: {:.4f}".format(epoch + 1, train_loss, val_loss))

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        patience_counter = 0

        torch.save(final_model.state_dict(), 'best_efficientnet.pth')
    else:
        patience_counter += 1
        print("Early stopping counter: {}".format(patience_counter))
        if patience_counter >= patience:
            print("\n조기 종료")
            break

print("학습 완료")

"""최종 모델 평가"""

test_model = CNN()
test_model.load_state_dict(torch.load('best_efficientnet.pth'))
test_model.eval()

test_preds = []
test_targets = []

with torch.no_grad():
    for x_test, y_test in test_loader:
        x_test, y_test = x_test.to(device), y_test.to(device)
        outputs = test_model(x_test)
        preds = torch.argmax(outputs, 1)

        test_preds.extend(preds.cpu().numpy())
        test_targets.extend(y_test.cpu().numpy())

final_accuracy = accuracy_score(test_targets, test_preds)
final_precision = precision_score(test_targets, test_preds, zero_division=0)
final_recall = recall_score(test_targets, test_preds, zero_division=0)

print("Accuracy: {:.4f}".format(final_accuracy))
print("Precision: {:.4f}".format(final_precision))
print("Recall: {:.4f}".format(final_recall))