# -*- coding: utf-8 -*-
"""finalbasemodel_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0kKak67fPvmZwMoqqgmAjkLK7UT5fE3
"""

import torch
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import random
from sklearn.metrics import precision_score, recall_score

USE_CUDA = torch.cuda.is_available()
device = torch.device("cuda" if USE_CUDA else "cpu")

random.seed(1)
torch.manual_seed(1)
if device == 'cuda':
    torch.cuda.manual_seed_all(1)

from google.colab import drive
drive.mount('/content/drive')

!cp /content/drive/MyDrive/archive.zip ./

!unzip archive.zip

class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.layer2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.layer3 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.fc = nn.Sequential(
            nn.Linear(28 * 28 * 128, 128),
            nn.ReLU(),
            nn.Linear(128, 2)
        )

    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = self.layer3(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        return out

training_epochs = 10
batch_size = 32
learning_rate = 0.001

data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

dataset_path = "fire_dataset"

full_dataset = dsets.ImageFolder(root=dataset_path, transform=data_transforms)

train_size = int(0.8 * len(full_dataset))
val_size = len(full_dataset) - train_size

train_dataset, val_dataset = torch.utils.data.random_split(
    full_dataset,
    [train_size, val_size],
    generator=torch.Generator().manual_seed(1)
)

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=False)

model = CNN().to(device)
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(train_loader)

    model.train()
    for x_train, y_train in train_loader:
        x_train = x_train.to(device)
        y_train = y_train.to(device)

        outputs = model(x_train)
        cost = criterion(outputs, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

    print("Epoch: {:02d}, cost = {:.4f}".format(epoch + 1, avg_cost))

print("학습 종료")

model.eval()
correct_count = 0
total_count = 0

all_predictions = []
all_targets = []

with torch.no_grad():
    for x_val, y_val in val_loader:
        x_val = x_val.to(device)
        y_val = y_val.to(device)

        prediction = model(x_val)

        correct_prediction = torch.argmax(prediction, 1) == y_val

        correct_count += correct_prediction.sum().item()
        total_count += y_val.size(0)

        preds = torch.argmax(prediction, 1)
        all_predictions.extend(preds.cpu().numpy())
        all_targets.extend(y_val.cpu().numpy())

    accuracy = correct_count / total_count
    print("Accuracy: {:.4f}".format(accuracy))

    precision = precision_score(all_targets, all_predictions, zero_division=0)
    recall = recall_score(all_targets, all_predictions, zero_division=0)

    print("Precision: {:.4f}".format(precision))
    print("Recall: {:.4f}".format(recall))